### ISSUE TITLE
Results on DND trained on sidd dataset

### ISSUE THREAD

**Issue by yarqian** [IDKiro/GMSNet#2]
Sorry to bother you again. When I just simply removed the synthetic data, the performance on DND is only 39.48db while the performance reported on the paper is 39.84db. So I am sorry to ask would you please give me some suggestions about that?
Many thanks.

**Comment by IDKiro** [comment]
I think this may be the same issue as your last issue. 
Sincerely, some tricks not mentioned in the paper are used to train the network (so almost all repos only provide test code).
Try your best, and I'll close this issue.
